INSERT INTO INVENTORY_ITEM (PRODUCT_ID, NAME, QUANTITY) VALUES ('BUSINESSCARD', 'Moo Business Card', 50);
INSERT INTO INVENTORY_ITEM (PRODUCT_ID, NAME, QUANTITY) VALUES ('POSTCARD', 'Moo Postcard', 20);
INSERT INTO INVENTORY_ITEM (PRODUCT_ID, NAME, QUANTITY) VALUES ('PEN', 'Moo Wonky pen', 5);
INSERT INTO INVENTORY_ITEM (PRODUCT_ID, NAME, QUANTITY) VALUES ('STICKER', 'Moo Amazing Sticker', 300);
INSERT INTO INVENTORY_ITEM (PRODUCT_ID, NAME, QUANTITY) VALUES ('flaky-item', 'Unreliable Item', 100);